[package]
name = "YouTubeThumbnailFixer"
version = "0.2.0"
edition = "2021"

[dependencies]
actix-web = "4"
regex = "1.11.1"
reqwest = { version = "0.12.12", features = ["blocking"] }
image = "0.25.5"
serde = { version = "1.0.217", features = ["derive"] }